import type { Metadata } from "next";
import { Geist, Geist_Mono, Sora } from "next/font/google";
import Navigation from "../components/navigation";
import Footer from "../components/footer";
import { NextIntlClientProvider } from "next-intl";
import { notFound } from "next/navigation";
import { VisitorTracker } from "../components/VisitorTracker";
import "../globals.css";

export function generateStaticParams() {
  return [{ locale: "en" }, { locale: "zh" }, { locale: "th" }];
}

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const sora = Sora({
  variable: "--font-sora",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Trip Ching mai",
  description: "Generated by create next app",
  icons: {
    icon: '/logo/logo.png',
  },
};

export default async function LocaleLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}) {
  const { locale } = await params;

  let messages;
  try {
    messages = (await import(`../../messages/${locale}.json`)).default;
  } catch {
    notFound();
  }

  return (
    <html lang={locale} className="h-full text-black-900">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${sora.variable} antialiased bg-gradient-to-t from-blue-400 to-orange-400 bg-fixed min-h-screen`}
      >
        <NextIntlClientProvider locale={locale} messages={messages}>
          <VisitorTracker />
          <div className="min-h-screen flex flex-col">
            <Navigation />
            <main className="container mx-auto pt-24 px-4 flex-1">
              {children}
            </main>
            <Footer />
          </div>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}