import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Navigation from "../components/navigation";
import Footer from "../components/footer";
import { NextIntlClientProvider } from "next-intl";
import { notFound } from "next/navigation";
import "../globals.css";

export function generateStaticParams() {
  return [{ locale: "en" }, { locale: "zh" }];
}

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Trip Ching mai",
  description: "Generated by create next app",
};

export default async function LocaleLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}) {
  const { locale } = await params;

  let messages;
  try {
    messages = (await import(`../../messages/${locale}.json`)).default;
  } catch {
    notFound();
  }

  return (
    <html lang={locale}>
      <body
      className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gradient-to-t from-blue-400 to-orange-400 text-black-900`}
      >
        <NextIntlClientProvider locale={locale} messages={messages}>
          <div
            className="min-h-screen flex flex-col"
            style={{ minHeight: "100vh", display: "flex", flexDirection: "column" }}
          >
            <Navigation />
            <main
              className="container mx-auto pt-24 px-4 flex-1"
              style={{ flex: "1 1 0%" }}
            >
              {children}
            </main>
            <Footer />
          </div>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
